version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/project
    steps:
      - checkout
      - run: python -V
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            python -m pytest -q tests

workflows:
  version: 2
  ci:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
